name: Docker

on:
  push:
    # Publish `name` branches as tags
    branches:
      - "*"
      - "!master"

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: |
          GIT_NAME=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          IMAGE_NAME=$(echo "$GIT_NAME" | cut -d"/" -f1)
          IMAGE_VERSION=$(echo "$GIT_NAME" | cut -d"/" -f2)
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME
          docker build . --file ./Dockerfile.$GIT_NAME --tag $IMAGE_ID:$IMAGE_VERSION

      - name: Push image
        run: |
          GIT_NAME=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          IMAGE_NAME=$(echo "$GIT_NAME" | cut -d"/" -f1)
          IMAGE_VERSION=$(echo "$GIT_NAME" | cut -d"/" -f2)
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME
          docker push $IMAGE_ID:$IMAGE_VERSION
